// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbGxutmUrNR_3JHTVMABFryRQ-LL-vzsM',
    appId: '1:920540205376:web:8ed535dd04cc07a5e22aa5',
    messagingSenderId: '920540205376',
    projectId: 'greenbite-26',
    authDomain: 'greenbite-26.firebaseapp.com',
    storageBucket: 'greenbite-26.firebasestorage.app',
    measurementId: 'G-Z8RS50SJ1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMonpPKM0uF4gioIdE-wscLrF_OTyR9jE',
    appId: '1:920540205376:android:7349e00341963435e22aa5',
    messagingSenderId: '920540205376',
    projectId: 'greenbite-26',
    storageBucket: 'greenbite-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNpOc_LqUvx2NjTdCzuZSYB9iIjb8px0',
    appId: '1:920540205376:ios:35b88d4afc26a54de22aa5',
    messagingSenderId: '920540205376',
    projectId: 'greenbite-26',
    storageBucket: 'greenbite-26.firebasestorage.app',
    iosBundleId: 'com.example.greenbiteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLNpOc_LqUvx2NjTdCzuZSYB9iIjb8px0',
    appId: '1:920540205376:ios:35b88d4afc26a54de22aa5',
    messagingSenderId: '920540205376',
    projectId: 'greenbite-26',
    storageBucket: 'greenbite-26.firebasestorage.app',
    iosBundleId: 'com.example.greenbiteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbGxutmUrNR_3JHTVMABFryRQ-LL-vzsM',
    appId: '1:920540205376:web:9a86f519a3bd0838e22aa5',
    messagingSenderId: '920540205376',
    projectId: 'greenbite-26',
    authDomain: 'greenbite-26.firebaseapp.com',
    storageBucket: 'greenbite-26.firebasestorage.app',
    measurementId: 'G-KEN22PBBB6',
  );
}
